version: '3.9'
services:
  client:
    image: node:18.12.0-alpine3.16
    working_dir: /home/travel-accommodation/
    command: npm run dev
    ports:
      - 4000:4000
    volumes:
      - .:/home/travel-accommodation/
    networks:
      - frontend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/travel-accommodation/server
    ports:
      - 8080:8080
    volumes:
      - .:/home/travel-accommodation/
    links:
      - postgres
    networks:
      - frontend
      - backend
  postgres:
    image: postgres:alpine3.16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=travel
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  frontend:
  backend:
