version: '3.9'
services:
  client:
    image: node:18.12.0-alpine3.16
    working_dir: /home/travel-accommodation/
    command: npx vite --port=4000
    ports:
      - "4000:4000"
    volumes:
      - .:/home/travel-accommodation/
    networks:
      - frontend
  server:
    image: golang:1.18.8-alpine3.16
    working_dir: /home/travel-accommodation/
    command: go run ./server/.
    ports:
      - "8080:8080"
    volumes:
      - .:/home/travel-accommodation/
    networks:
      - frontend
      - backend
  db:
    image: postgres:alpine3.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
volumes:
  postgres-data:

networks:
  frontend:
  backend: